### ISSUE TITLE
Handle Other Currencies

### ISSUE THREAD

**Issue by ocomsoft** [grails-plugins/grails-paypal#10]
The current code doesn't seem to handle other currencies.

For example putting
<paypal:button .... currency="AUD"  ... >

A valid currency (I think)
The Payment class has the following error in the errors

Field error in object 'org.grails.paypal.Payment' on field 'currency': rejected value [AUD]; codes [org.grails.paypal.Payment.currency.typeMismatch.error,org.grails.paypal.Payment.currency.typeMismatch,payment.currency.typeMismatch.error,payment.currency.typeMismatch,typeMismatch.org.grails.paypal.Payment.currency,typeMismatch.currency,typeMismatch.java.util.Currency,typeMismatch]; arguments [currency]; default message [Could not find matching constructor for: java.util.Currency(java.lang.String)]

**Comment by Dhanendra-jft** [comment]
@ocomsoft I think you can close this issue as the suggestion solves your problem also Graeme Rocher has proposed to add a currency converter to Grails core which will help others.
