### ISSUE TITLE
Cancelled Payments are fraud risky

### ISSUE THREAD

**Issue by mhashem** [grails-plugins/grails-paypal#12]
The plugin documentation is weak, in the following snippet of the PayPalController.groovy you attempt to switch any payment.status to Completed

```java
def success = {
		def payment = Payment.findByTransactionId(params.transactionId)
		log.debug "Success notification received from PayPal for $payment with transaction id ${params.transactionId}"
		if (payment) {
			request.payment = payment
			if (payment.status != Payment.COMPLETE) {
				payment.status = Payment.COMPLETE
				payment.save(flush: true)
			}

			if (params.returnAction || params.returnController) {
				def args = [:]
				if (params.returnAction) args.action = params.returnAction
				if (params.returnController) args.controller = params.returnController
				args.params = params
				redirect(args)
			}
			else {
				return [payment: payment]
			}
		}
		else {
			response.sendError 403
		}
	}
```

thus lets assume a payment is cancelled and the transactionId was hijacked in a way or another, issuing the same request in but to a success action using the same transactionId will proceed to a successful payment depending on what you provide here:

```java
paymentReceivedFilter(controller:'paypal', action:'(success|notifyPaypal)') {
  after = {
     def payment = request.payment
     if(payment && payment.status == org.grails.paypal.Payment.COMPLETE) {
         def payment = IPodPayment.findByPayment(request.payment)
         payment.shipIt()
     }
  }
}
```

I might be wrong or this case wont occur at anytime, but I am junior developer using grails since 1 and half year and I had this issue while testing, I will be very pleased if you revise this and thanks in advance.

**Comment by graemerocher** [comment]
The plugin doesn't enforce any additional layers of security, if you want that then of course you can add additional filters and / or interceptors to perform additional security checks, but that is beyond the scope of the plugin.
